[[main]]
  name       = 'Home'
  identifier = 'home'
  pageRef    = '/'
  weight     = 1

[[main]]
  name       = 'About Me'
  identifier = 'aboutme'
  pageRef    = '/aboutme'
  weight     = 3

[[main]]
  name       = 'All Games'
  identifier = 'games'
  pageRef    = '/post/'
  weight     = 2

  [[main]]
  name       = 'Professional Experiences'
  identifier = 'professional'
  pageRef    = '/categories/1_professionalexperiences/'
  Post       = 'Work related projects'
  parent     = 'games'
  weight     = 1

  [[main]]
  name       = 'Personal Projects'
  identifier = 'personal'
  pageRef    = '/categories/2_personalprojects/'
  Post       = 'Personal projects'
  parent     = 'games'
  weight     = 2

  [[main]]
  name       = 'By Engine'
  identifier = 'engine'
  parent     = 'games'
  pageRef    = '/tags/'
  weight     = 4

  [[main]]
    name       = 'Unity'
    identifier = 'unity'
    pageRef    = '/tags/unity'
    parent     = 'engine'
    Post       = 'Games made with Unity'
    weight     = 1

  [[main]]
    name       = 'Unreal'
    identifier = 'unreal'
    pageRef    = '/tags/unreal'
    parent     = 'engine'
    Post       = 'Games made with Unreal'
    weight     = 2
  
  [[main]]
    name       = 'Godot'
    identifier = 'godot'
    pageRef    = '/tags/godot'
    parent     = 'engine'
    Post       = 'Games made with Godot'
    weight     = 3

  [[main]]
    name       = 'Game Jams'
    identifier = 'jams'
    pageRef    = '/categories/3_gamejams/'
    parent     = 'games'
    Post       = 'Games submitted in game jams'
    weight     = 3

[[main]]
  name       = 'Resume'
  identifier = 'resume'
  weight     = 4
  url        = '/resume'

[[main]]
  name       = 'Blog'
  identifier = 'blog'
  pageRef    = '/categories/4_blog'
  weight     = 5

[[main]]
  name       = 'Contact'
  identifier = 'contact'
  pageRef    = '/contact'
  weight     = 6

