baseURL = 'https://hugo-portfolio-bvx.pages.dev/'
languageCode = 'en-us'
title = 'Zheng Yi Hu'
theme = "hugo-brewm"
[params.logo]
       logoType = true
       logoMark = '/hugo_portfolio/medias/logo.svg' 
[security]
  enableInlineShortcodes = true
[markup.goldmark.renderer] 
  unsafe= true
[caches]
  [caches.images]
    dir = ':cacheDir/images'
## Typography settings
[params.typeface]
    ## Use web safe fonts (will overide font selection below)
    webSafe = false
    ## Serif font selection
    roman = 'crimson'
    ## Sans-serif font selection
    sans = 'inter'
    ## use typeface stored in local server (pleaase download font's uri first)
    localHost = false

## Enable Git information for pages, (e.g. lastMod date information)
enableGitInfo = true
## Convert all URLs to absolute URLs
canonifyURLs = false